'use client'
import { useApollo } from '@/utils/apollo'
import './globals.css'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { css } from '@emotion/react'
import { Colors } from '@/colors/colors'
import ApolloContext from '@/contexts/ApolloContext'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const flexed = css({
  flex: 1,
  backgroundColor: Colors.grayBackground,
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApolloContext>
      <html lang="en">
        <body css={flexed} className={inter.className}>
          {children}
        </body>
      </html>
    </ApolloContext>
  )
}
