'use client'
import { useApollo } from '@/utils/apollo'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ApolloProvider } from '@apollo/client'
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";
import { css } from '@emotion/react'
import { Colors } from '@/colors/colors'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const flexed = css({
  flex: 1,
  backgroundColor: Colors.grayBackground,
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const client = useApollo();

  // Trace Errors
  if (process.env.NODE_ENV !== "production") {
    loadDevMessages();
    loadErrorMessages();
  }

  return (
    <ApolloProvider client={client}>
      <html lang="en">
        <body css={flexed} className={inter.className}>
          {children}
        </body>
      </html>
    </ApolloProvider>
  )
}
